// Header

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: warreport.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The convention indicates that enum should be declared before the messages
type Countries int32

const (
	Countries_countries_unknown Countries = 0
	Countries_usa               Countries = 1
	Countries_rus               Countries = 2
	Countries_chn               Countries = 3
	Countries_esp               Countries = 4
	Countries_gtm               Countries = 5
)

// Enum value maps for Countries.
var (
	Countries_name = map[int32]string{
		0: "countries_unknown",
		1: "usa",
		2: "rus",
		3: "chn",
		4: "esp",
		5: "gtm",
	}
	Countries_value = map[string]int32{
		"countries_unknown": 0,
		"usa":               1,
		"rus":               2,
		"chn":               3,
		"esp":               4,
		"gtm":               5,
	}
)

func (x Countries) Enum() *Countries {
	p := new(Countries)
	*p = x
	return p
}

func (x Countries) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Countries) Descriptor() protoreflect.EnumDescriptor {
	return file_warreport_proto_enumTypes[0].Descriptor()
}

func (Countries) Type() protoreflect.EnumType {
	return &file_warreport_proto_enumTypes[0]
}

func (x Countries) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Countries.Descriptor instead.
func (Countries) EnumDescriptor() ([]byte, []int) {
	return file_warreport_proto_rawDescGZIP(), []int{0}
}

// WarReportRequest about the war report
type WarReportRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Country         Countries              `protobuf:"varint,1,opt,name=country,proto3,enum=wartweets.Countries" json:"country,omitempty"`
	WarplanesInAir  int32                  `protobuf:"varint,2,opt,name=warplanes_in_air,json=warplanesInAir,proto3" json:"warplanes_in_air,omitempty"`
	WarshipsInWater int32                  `protobuf:"varint,3,opt,name=warships_in_water,json=warshipsInWater,proto3" json:"warships_in_water,omitempty"`
	Timestamp       string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WarReportRequest) Reset() {
	*x = WarReportRequest{}
	mi := &file_warreport_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WarReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WarReportRequest) ProtoMessage() {}

func (x *WarReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_warreport_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WarReportRequest.ProtoReflect.Descriptor instead.
func (*WarReportRequest) Descriptor() ([]byte, []int) {
	return file_warreport_proto_rawDescGZIP(), []int{0}
}

func (x *WarReportRequest) GetCountry() Countries {
	if x != nil {
		return x.Country
	}
	return Countries_countries_unknown
}

func (x *WarReportRequest) GetWarplanesInAir() int32 {
	if x != nil {
		return x.WarplanesInAir
	}
	return 0
}

func (x *WarReportRequest) GetWarshipsInWater() int32 {
	if x != nil {
		return x.WarshipsInWater
	}
	return 0
}

func (x *WarReportRequest) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

// WarReportResponse about the war report
type WarReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WarReportResponse) Reset() {
	*x = WarReportResponse{}
	mi := &file_warreport_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WarReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WarReportResponse) ProtoMessage() {}

func (x *WarReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_warreport_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WarReportResponse.ProtoReflect.Descriptor instead.
func (*WarReportResponse) Descriptor() ([]byte, []int) {
	return file_warreport_proto_rawDescGZIP(), []int{1}
}

func (x *WarReportResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_warreport_proto protoreflect.FileDescriptor

const file_warreport_proto_rawDesc = "" +
	"\n" +
	"\x0fwarreport.proto\x12\twartweets\"\xb6\x01\n" +
	"\x10WarReportRequest\x12.\n" +
	"\acountry\x18\x01 \x01(\x0e2\x14.wartweets.CountriesR\acountry\x12(\n" +
	"\x10warplanes_in_air\x18\x02 \x01(\x05R\x0ewarplanesInAir\x12*\n" +
	"\x11warships_in_water\x18\x03 \x01(\x05R\x0fwarshipsInWater\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\"+\n" +
	"\x11WarReportResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status*O\n" +
	"\tCountries\x12\x15\n" +
	"\x11countries_unknown\x10\x00\x12\a\n" +
	"\x03usa\x10\x01\x12\a\n" +
	"\x03rus\x10\x02\x12\a\n" +
	"\x03chn\x10\x03\x12\a\n" +
	"\x03esp\x10\x04\x12\a\n" +
	"\x03gtm\x10\x052[\n" +
	"\x10WarReportService\x12G\n" +
	"\n" +
	"SendReport\x12\x1b.wartweets.WarReportRequest\x1a\x1c.wartweets.WarReportResponseB\tZ\a./protob\x06proto3"

var (
	file_warreport_proto_rawDescOnce sync.Once
	file_warreport_proto_rawDescData []byte
)

func file_warreport_proto_rawDescGZIP() []byte {
	file_warreport_proto_rawDescOnce.Do(func() {
		file_warreport_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_warreport_proto_rawDesc), len(file_warreport_proto_rawDesc)))
	})
	return file_warreport_proto_rawDescData
}

var file_warreport_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_warreport_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_warreport_proto_goTypes = []any{
	(Countries)(0),            // 0: wartweets.Countries
	(*WarReportRequest)(nil),  // 1: wartweets.WarReportRequest
	(*WarReportResponse)(nil), // 2: wartweets.WarReportResponse
}
var file_warreport_proto_depIdxs = []int32{
	0, // 0: wartweets.WarReportRequest.country:type_name -> wartweets.Countries
	1, // 1: wartweets.WarReportService.SendReport:input_type -> wartweets.WarReportRequest
	2, // 2: wartweets.WarReportService.SendReport:output_type -> wartweets.WarReportResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_warreport_proto_init() }
func file_warreport_proto_init() {
	if File_warreport_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_warreport_proto_rawDesc), len(file_warreport_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_warreport_proto_goTypes,
		DependencyIndexes: file_warreport_proto_depIdxs,
		EnumInfos:         file_warreport_proto_enumTypes,
		MessageInfos:      file_warreport_proto_msgTypes,
	}.Build()
	File_warreport_proto = out.File
	file_warreport_proto_goTypes = nil
	file_warreport_proto_depIdxs = nil
}
